export const All = '全部'
export enum STATUS {
  LIST = 'list',
  DETAILS = 'details',
}
export const locations = [
  {
    value: All,
    label: All,
  },
  {
    value: '保定',
    label: '保定',
  },
  {
    value: '承德',
    label: '承德',
  },
  {
    value: '沧州',
    label: '沧州',
  },
  {
    value: '邯郸',
    label: '邯郸',
  },
  {
    value: '衡水',
    label: '衡水',
  },
  {
    value: '廊坊',
    label: '廊坊',
  },
  {
    value: '秦皇岛',
    label: '秦皇岛',
  },
  {
    value: '石家庄桥西',
    label: '石家庄桥西',
  },
  {
    value: '石家庄桥东',
    label: '石家庄桥东',
  },
  {
    value: '石家庄金融',
    label: '石家庄金融',
  },
  {
    value: '唐山',
    label: '唐山',
  },
  {
    value: '邢台',
    label: '邢台',
  },
  {
    value: '张家口',
    label: '张家口',
  },
]

export const years = [
  {
    label: All,
    value: All,
  },
  {
    label: '2023',
    value: '2023',
  },
  {
    label: '2024',
    value: '2024',
  },
  {
    label: '2025',
    value: '2025',
  },
  {
    label: '2026',
    value: '2026',
  },
  {
    label: '2027',
    value: '2027',
  },
  {
    label: '2028',
    value: '2028',
  },
  {
    label: '2029',
    value: '2029',
  },
]

export enum subjectType {
  GGK = '公共课',
  ZYK = '专业课',
  QKK = '全科课',
  TSK = '特色课',
}
export const subjects = [
  {
    label: All,
    value: All,
  },
  {
    label: '公共课',
    value: '公共课',
  },
  {
    label: '专业课',
    value: '专业课',
  },
  {
    label: '全科课',
    value: '全科课',
  },
  {
    label: '特色课',
    value: '特色课',
  },
]

export const courses = [
  {
    id: 1,
    image: '1.png',
    typeTitle: 'course_center_qkk.png',
    type: subjectType.QKK,
    title: '28届领学通关班',
    secTitle: '领学通关，一站上岸',
    startDate: '2025-09-09 00:00:00',
    tags: [],
    vetifyNumber: 12088,
    location: '',
    time: '',
    year: 2028,
    detailImages: ['a1.png', 'a2.png', 'a3.png', 'a4.png', 'a5.png'],
  },
  {
    id: 2,
    image: '1.png',
    type: subjectType.QKK,
    title: '27届领学通关班',
    secTitle: '领学通关，一站上岸',
    startDate: '2025-10-11 15:33:23',
    tags: [],
    location: '',
    vetifyNumber: 6849,
    time: '',
    year: 2027,
    detailImages: ['a1.png', 'a2.png', 'a3.png', 'a4.png', 'a5.png'],
  },
  {
    id: 3,
    image: '2.jpg',
    type: subjectType.TSK,
    title: '26届全程营',
    secTitle: '封闭式集训直至考前',
    startDate: '2025-09-20 14:16:55',
    tags: [],
    location: '',
    vetifyNumber: 3075,
    time: '',
    year: 2026,
    detailImages: ['c1.jpg', 'c2.jpg', 'c3.jpg'],
  },
  {
    id: 4,
    image: '3.jpg',
    type: subjectType.TSK,
    title: '超越营',
    secTitle: '封闭集训海量习题模考，全真模拟考试，找出知识盲区，查漏补缺，提分见效快。',
    startDate: '2024-07-23 18:01:07',
    tags: [],
    location: '',
    vetifyNumber: 6956,
    time: '',
    year: 2026,
    detailImages: ['d1.jpg', 'd2.jpg', 'd3.jpg', 'd4.jpg'],
  },
  {
    id: 5,
    image: '4.jpg',
    type: subjectType.TSK,
    title: '个性化一对一',
    secTitle: '领学通关，一站上岸',
    startDate: '2024-07-21 14:37:18',
    tags: [],
    location: '',
    vetifyNumber: 1140,
    time: '',
    year: 2026,
    detailImages: ['e1.jpg', 'e2.jpg', 'e3.jpg', 'e4.jpg'],
  },
  {
    id: 6,
    image: '5.jpg',
    type: subjectType.TSK,
    title: '艺路畅学计划',
    secTitle: '零基础、无规划、自制力薄弱的同学，定制加速赛道',
    startDate: '2024-07-16 09:57:50',
    tags: [],
    vetifyNumber: 21720,
    location: '',
    time: '',
    year: 2026,
    detailImages: ['f1.jpg', 'f2.jpg', 'f3.jpg', 'f4.jpg', 'f5.jpg'],
  },
  {
    id: 7,
    image: '2.jpg',
    type: subjectType.QKK,
    title: '2027届升本全程营',
    secTitle: '适用于2027年专升本，封闭集训考生',
    startDate: '2025-09-18 00:00:00',
    tags: [],
    vetifyNumber: 307,
    location: '',
    time: '',
    year: 2027,
    detailImages: ['g1.png', 'g2.png', 'g3.png'],
  },
  {
    id: 8,
    image: '5.jpg',
    type: subjectType.QKK,
    title: '艺路畅学计划',
    secTitle: '艺路陪伴，专属艺术课程',
    startDate: '2025-09-18 00:00:00',
    tags: [],
    vetifyNumber: 1357,
    location: '',
    time: '',
    year: 2027,
    detailImages: ['f1.jpg', 'f2.jpg', 'f3.jpg', 'f4.jpg', 'f5.jpg'],
  },
  {
    id: 9,
    image: '6.jpg',
    type: subjectType.GGK,
    title: '公共课领学通关班',
    secTitle: '领学通关班公共课部分',
    startDate: '2025-09-09 00:00:00',
    tags: [],
    vetifyNumber: 3506,
    location: '',
    time: '',
    year: 2027,
    detailImages: ['h1.png'],
  },
  {
    id: 10,
    image: '1.png',
    type: subjectType.QKK,
    title: '26届领学通关班',
    secTitle: '领学通关班，助力圆梦本科！',
    startDate: '2025-07-09 15:47:11',
    tags: [],
    vetifyNumber: 23178,
    location: '',
    time: '',
    year: 2026,
    detailImages: ['a1.png', 'a2.png', 'a3.png', 'a4.png', 'a5.png'],
  },
  {
    id: 11,
    image: '7.png',
    type: subjectType.ZYK,
    title: '领学通关A班',
    secTitle: '适用退役士兵考生，仅专业课部分',
    startDate: '2024-10-11 15:31:32',
    tags: [],
    vetifyNumber: 5167,
    location: '',
    time: '',
    year: 2027,
    detailImages: ['i1.png', 'i2.png'],
  },
  {
    id: 12,
    image: '8.png',
    type: subjectType.GGK,
    title: '领学通关班-公共课考点精研',
    secTitle: '领学通关班-公共课考点精研',
    startDate: '2024-07-29 16:13:00',
    tags: [],
    vetifyNumber: 10008,
    location: '',
    time: '',
    year: 2026,
    detailImages: ['j1.jpg', 'j2.jpg', 'j3.jpg', 'j4.jpg'],
  },
  {
    id: 13,
    image: '9.jpg',
    type: subjectType.TSK,
    title: 'VIP定向班',
    secTitle: '考前五个月的封闭集训，老师全程伴学',
    startDate: '2024-07-16 10:21:31',
    tags: [],
    vetifyNumber: 15541,
    location: '',
    time: '',
    year: 2026,
    detailImages: ['k1.png', 'k2.png', 'k3.png', 'k4.png', 'k5.png', 'k6.png'],
  },
]
